name: Update CIDRs

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8.16
        uses: actions/setup-python@v3
        with:
          python-version: "3.8.16"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run
        run: python3 NetblockTool.py -v Google -o data/datacenters
      - name: Push updates
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.email "action@github.com";
            git config --global user.name "Update Bot";
            git add data;
            git commit -m "Updated CIDRs on $(date -Iminutes)";
            git push;
          else
            echo "no changes";
          fi
